
flags: {}
packages:
  - '.'
  - location: ./dep/graphted
    extra-dep: false
  # - location: ./dep/indexed
  #   extra-dep: true
  # - location: ./dep/deepseq
  #   extra-dep: true
  # - location: 
  #     git: git@github.com:goldfirere/singletons.git
  #     commit: f6516af95f2421f9509abfb992523d430e00b6ad
  #   extra-dep: true
  # - location:
  #     git: git@github.com:goldfirere/th-desugar.git
  #     commit: 97567a887c0fab84889bd22894151b3576bd616e
  #   extra-dep: true
allow-newer: true
resolver: lts-8.12

# GHC 8.2.1: (not working with Intero)
# resolver: ghc-8.2.0.20170404
# compiler: ghc-8.2.0.20170404
# compiler-check: match-exact
# extra-deps:
#   - StateVar-1.1.0.4
#   - adjunctions-4.3
#   - base-orphans-0.6
#   - bifunctors-5.4.2
#   - cabal-doctest-1
#   - comonad-5.0.1
#   - contravariant-1.4
#   - distributive-0.5.2
#   - exceptions-0.8.3
#   - free-4.12.4
#   - hashable-1.2.6.0
#   - kan-extensions-5.0.1
#   - lens-4.15.2
#   - mtl-2.2.1
#   - parallel-3.2.1.1
#   - prelude-extras-0.4.0.3
#   - primitive-0.6.2.0
#   - profunctors-5.2
#   - reflection-2.1.2
#   - semigroupoids-5.2
#   - semigroups-0.18.3
#   - stm-2.4.4.1
#   - tagged-0.8.5
#   - text-1.2.2.1
#   - transformers-compat-0.5.1.4
#   - unordered-containers-0.2.8.0
#   - vector-0.12.0.1
#   - void-0.7.2
#   - syb-0.7
#   - ghc-paths-0.1.0.9

# See Note [ghc-mod bug]
# apply-ghc-options: everything
# ghc-options:
#   "*": -opta-Wa,-mrelax-relocations=no -j4

# Note [ghc-mod bug]
# ~~~~~~~~~~~~~~~~~~
# These options were created to fix https://github.com/DanielG/ghc-mod/issues/762
# tl;dr: a type of dynamic relocation is not supported by ghc, need to disable
# These options can be removed for GHC >= 7.10.4 || >= 8.0.2
